#*******************************************************************************
# Copyright (C), 2008-2016, OPPO Mobile Comm Corp., Ltd.
# ODM_WT_EDIT
# FILE: - Makefile
# Description : Makefile for the Novatek NT36xxx touchscreen driver.
# Version: 1.0
# Date : 2018/5/8
#
# -------------------------Revision History:----------------------------------
#  <author>	 <data> 	<version >			<desc>
#
#
#*******************************************************************************/

obj-$(CONFIG_INPUT_TOUCHSCREEN_NT36525) += nt36xxx.o nt36xxx_fw_update.o nt36xxx_ext_proc.o nt36xxx_mp_ctrlram.o
