############################################################
## Copyright (C), 2008-2016, OPPO Mobile Comm Corp., Ltd.
## ODM_WT_EDIT
## File: - Makefile
## Description: kernel fingerprint Makefile.
##
## Version: V00-01-00-25
## Date : 2018/06/26
##
## ------------------------------- Revision History: -------------------------------
##  	<author>		<data> 	   <version >	       <desc>
##	
##
#############################################################
obj-$(CONFIG_FINGERPRINT_FPC_1020) += fpc1020_platform_tee.o
