obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
#ifdef VENDOR_EDIT
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#endif /* VENDOR_EDIT */
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
#ifdef VENDOR_EDIT
obj-y     +=  oppo_healthinfo/
#endif /* VENDOR_EDIT */
