#*******************************************************************************
# Copyright (C), 2008-2018, OPPO Mobile Comm Corp., Ltd.
# ODM_WT_EDIT
# FILE: - Makefile
# Description : This program is for ili9881 driver Makefile
# Version: 1.0
# Date : 2018/5/14
#
# -------------------------Revision History:----------------------------------
#  <author>	 <data> 	<version >			<desc>
#
#
#*****************************************************************************/
obj-$(CONFIG_TOUCHSCREEN_ILI9881) := platform.o userspace.o
obj-$(CONFIG_TOUCHSCREEN_ILI9881) += core/config.o \
                                     core/finger_report.o \
									 core/firmware.o \
									 core/flash.o \
		                             core/i2c.o \
		                             core/spi.o \
		                             core/mp_test.o \
		                             core/protocol.o \
		                             core/parser.o \
		                             core/gesture.o


