#*******************************************************************************
# Copyright (C), 2008-2016, OPPO Mobile Comm Corp., Ltd.
# ODM_WT_EDIT
# FILE: - Makefile
# Description : Makefile for the Himax touchscreen driver.
# Version: 1.0
# Date : 2018/5/22
#
# -------------------------Revision History:----------------------------------
#  <author>	 <data> 	<version >			<desc>
#
#
#*******************************************************************************/
obj-$(CONFIG_TOUCHSCREEN_HIMAX_INCELL)   			+=	himax_ic_incell_core.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83102)   	+=	himax_ic_HX83102.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_COMMON)   			+=	himax_common.o himax_platform.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_DEBUG)   			+=	himax_debug.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_INSPECT)   		+=	himax_inspection.o